import React, { useState, useEffect, useRef } from "react";
import { useParams } from "react-router-dom";
import Sidebar from "../../partials/Sidebar";
import Header from "../../partials/Header";
import { toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { useReactToPrint } from "react-to-print";
import { FaPrint } from "react-icons/fa";

import logo from '../../images/logo_p.jpg'; // Ensure this path is correct

// Helper function to format date
const formatDate = (dateString) => {
  if (!dateString) return "N/A";
  const date = new Date(dateString);
  const day = String(date.getDate()).padStart(2, '0');
  const month = String(date.getMonth() + 1).padStart(2, '0');
  const year = date.getFullYear();
  return `${day}-${month}-${year}`;
};

// Component to render the footer
const CustomerReportFooter = () => {
  const currentTime = new Date().toLocaleString('en-BD', {
    timeZone: 'Asia/Dhaka',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
  });
  return (
    <div className="mt-8 text-center text-gray-500 text-sm print-footer border-t-2 border-gray-200 pt-4">
      <p>Report generated by Pleasure BD on {currentTime}</p>
      <p>Visit our website: <a href="https://pleasurebd.com" target="_blank" rel="noopener noreferrer" className="text-blue-600 hover:underline">www.pleasurebd.com</a></p>
      <p className="mt-2">This report is for internal use only. All rights reserved.</p>
    </div>
  );
};

// Component to render the customer report content, including the header
const CustomerReportContent = ({ customer, showHeader = false }) => {
  const activeMembership = customer.active_membership;
  const allMemberships = customer.memberships || [];

  return (
    <div className="bg-white rounded-lg shadow-xl overflow-hidden p-2">
      {/* Header for the print view */}
      {showHeader && (
        <>
          <div className="w-full bg-[#0097A7] rounded px-6 py-4 flex items-center justify-between mb-6">
            <div className="flex-shrink-0">
              <img src={logo} alt="Company Logo" className="h-16 w-16 rounded object-contain" />
            </div>
            <div className="text-center text-white">
              <h1 className="text-xl font-bold">PLEASURE BANGLADESH LIMITED</h1>
              <p className="text-sm">Corporate Address: Zaman Tower, 11th floor, Flat:1115, Purana Palton, Dhaka</p>
              <p className="text-sm">Mobile: +880 1234 567890</p>
            </div>
            <div className="flex-shrink-0"></div>
          </div>
          <h1 className="text-3xl font-bold text-gray-800 border-b-2 pb-2 mb-4">Customer Report</h1>
        </>
      )}
      
      {/* This header is always visible on the web page */}
      <div className="w-full bg-[#0097A7] rounded px-3 sm:px-6 lg:px-6 py-4 flex items-center justify-between print-hidden">
        <div className="flex-shrink-0">
          <img src={logo} alt="Company Logo" className="h-16 w-16 rounded object-contain" />
        </div>
        <div className="text-center text-white">
          <h1 className="text-xl font-bold">PLEASURE BANGLADESH LIMITED</h1>
          <p className="text-sm">Corporate Address: Zaman Tower, 11th floor, Flat:1115, Purana Palton, Dhaka</p>
          <p className="text-sm">Mobile: +880 1234 567890</p>
        </div>
        <div className="flex-shrink-0"></div>
      </div>

      {/* Personal Information */}
      <div className="mb-6 bg-gray-50 p-4 rounded-lg">
        <h2 className="text-2xl font-semibold text-teal-600 mb-1">Personal Information</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 text-gray-700">
          <p><strong>Name (EN):</strong> {customer.full_name_en || "N/A"}</p>
          <p><strong>Name (BN):</strong> {customer.full_name_bn || "N/A"}</p>
          <p><strong>Phone:</strong> {customer.phone || "N/A"}</p>
          <p><strong>Email:</strong> {customer.email || "N/A"}</p>
          <p><strong>NID:</strong> {customer.national_id || "N/A"}</p>
          <p><strong>Date of Birth:</strong> {formatDate(customer.dob)}</p>
          <p><strong>Gender:</strong> {customer.gender || "N/A"}</p>
        </div>
        <div className="mt-4 text-gray-700">
          <p><strong>Present Address:</strong> {customer.present_address || "N/A"}</p>
          <p><strong>Permanent Address:</strong> {customer.permanent_address || "N/A"}</p>
        </div>
      </div>

      {/* Active Membership */}
      {activeMembership ? (
        <div className="mb-6 bg-green-50 border-l-4 border-green-500 p-4 rounded-lg shadow-sm">
          <h2 className="text-2xl font-semibold text-green-700 mb-2">Active Membership</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 text-gray-700">
            <p><strong>Membership No:</strong> {activeMembership.membership_no}</p>
            <p><strong>Card No:</strong> {activeMembership.physical_card_no || "N/A"}</p>
            <p><strong>Plan:</strong> {activeMembership.plan.name}</p>
            <p><strong>Price:</strong> {activeMembership.plan.price} {activeMembership.plan.currency}</p>
            <p><strong>Start Date:</strong> {formatDate(activeMembership.start_date)}</p>
            <p><strong>End Date:</strong> {formatDate(activeMembership.end_date)}</p>
          </div>
        </div>
      ) : (
        <div className="mb-6 bg-red-50 border-l-4 border-red-500 p-4 rounded-lg shadow-sm">
          <h2 className="text-2xl font-semibold text-red-700 mb-2">Active Membership</h2>
          <p className="text-gray-500">No active membership found.</p>
        </div>
      )}

      {/* Dependent Members */}
      {activeMembership && activeMembership.members?.length > 0 && (
        <div className="mb-6 bg-blue-50 border-l-4 border-blue-500 p-4 rounded-lg shadow-sm">
          <h2 className="text-2xl font-semibold text-blue-700 mb-2">Dependent Members</h2>
          <ul className="list-none space-y-3 text-gray-700">
            {activeMembership.members.map((member, index) => (
              <li key={index} className="p-3 bg-white border rounded-md">
                <p><strong>Name:</strong> {member.full_name || "N/A"}</p>
                <p><strong>Relation:</strong> {member.relation || "N/A"}</p>
                <p><strong>Phone:</strong> {member.phone || "N/A"}</p>
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* All Memberships History */}
      {allMemberships?.length > 0 && (
        <div className="mb-6 bg-indigo-50 border-l-4 border-indigo-500 p-4 rounded-lg shadow-sm">
          <h2 className="text-2xl font-semibold text-indigo-700 mb-4">Membership History</h2>
          <div className="space-y-6">
            {allMemberships?.map((membership, index) => (
              <div key={index} className="p-4 bg-white rounded-md shadow-sm border border-gray-200">
                <div className="flex justify-between items-center mb-2">
                  <h3 className="text-lg font-bold text-gray-800">{membership.plan.name}</h3>
                  <span className={`px-3 py-1 text-xs font-semibold rounded-full ${membership.status === 'active' ? 'bg-green-100 text-green-800' : 'bg-red-100 text-red-800'}`}>
                    {membership.status.toUpperCase()}
                  </span>
                </div>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 text-sm text-gray-600">
                  <p><strong>Membership No:</strong> {membership.membership_no}</p>
                  <p><strong>Card No:</strong> {membership.physical_card_no || "N/A"}</p>
                  <p><strong>Period:</strong> {formatDate(membership.start_date)} - {formatDate(membership.end_date)}</p>
                  <p><strong>Price:</strong> {membership.plan.price} {membership.plan.currency}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}
      
      <CustomerReportFooter />
    </div>
  );
};

const CustomerDetails = () => {
  const { id } = useParams();
  const [customer, setCustomer] = useState(null);
  const [loading, setLoading] = useState(true);
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const token = localStorage.getItem("token");

  const componentRef = useRef();

  const handlePrint = useReactToPrint({
    content: () => componentRef.current,
    documentTitle: `Customer Report - ${id}`,
  });

  useEffect(() => {
    const fetchCustomerDetails = async () => {
      try {
        const res = await fetch(
          `https://pleasurebd.com/pleasure-backend/public/api/v1/customers/${id}`,
          { headers: { Authorization: `Bearer ${token}` } }
        );
        const data = await res.json();
        if (res.ok) {
          setCustomer(data);
        } else {
          toast.error("Customer not found.");
        }
      } catch (err) {
        console.error("Failed to fetch customer details:", err);
        toast.error("Failed to fetch customer details.");
      } finally {
        setLoading(false);
      }
    };

    if (id) {
      fetchCustomerDetails();
    }
  }, [id, token]);

  if (loading) {
    return (
      <div className="flex justify-center items-center h-screen">
        <div className="w-12 h-12 border-4 border-teal-600 border-t-transparent rounded-full animate-spin"></div>
        <p className="ml-4 text-gray-600">Loading customer details...</p>
      </div>
    );
  }

  if (!customer) {
    return <div className="p-8 text-center text-red-600">No customer data available.</div>;
  }

  return (
    <div className="flex h-screen overflow-hidden">
      <Sidebar sidebarOpen={sidebarOpen} setSidebarOpen={setSidebarOpen} />
      <div className="relative flex flex-col flex-1 overflow-y-auto overflow-x-hidden">
        <Header sidebarOpen={sidebarOpen} setSidebarOpen={setSidebarOpen} />
        <main className="lg:p-4 p-2">
          {/* Main visible content container */}
          <div className="max-w-5xl mx-auto mt-0">
            <div className="flex justify-between items-center mb-2">
              <h1 className="text-2xl font-bold text-dark dark:text-white">
                Customer Details Info
              </h1>
              <button
                onClick={handlePrint}
                className="flex items-center gap-2 bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-md transition-colors"
              >
                <FaPrint /> Print Report
              </button>
            </div>
            
            <hr className="mb-6"/>

            <CustomerReportContent customer={customer} />
          </div>
        </main>
        
        {/* Hidden component for printing */}
        <div style={{ display: "none" }}>
          <div ref={componentRef} className="p-8 font-sans">
            <div className="max-w-4xl mx-auto">
              <CustomerReportContent customer={customer} showHeader={true} />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default CustomerDetails;